name: Upbit Technical Analysis Alert

on:
  schedule:
    # 매시간 정시에 실행 (UTC 기준)
    - cron: '0 * * * *'
  workflow_dispatch:  # 수동 실행 가능
  push:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Upbit analysis
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        LOG_LEVEL: INFO
      run: |
        python upbit_alert_cloud.py
        
    - name: Upload logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: analysis-logs
        path: upbit_alert.log
        retention-days: 7 